export const REQUEST_PARKING_COST_SUCCESS = 'REQUEST_PARKING_COST_SUCCESS';
export const REQUEST_PARKING_COST_ERROR = 'REQUEST_PARKING_COST_ERROR';
export const PARKING_FORM_TYPE = 'PARKING_FORM_TYPE';
export const PARKING_RATE = 'PARKING_RATE';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const SET_IS_SIGNED_IN = 'SET_IS_SIGNED_IN';
export const SIGNING_ERROR = 'SIGNING_ERROR';
export const SIGN_UP_IS_SHOWN = 'SIGN_UP_IS_SHOWN';
export const SIGN_IN_IS_SHOWN = 'SIGN_IN_IS_SHOWN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_IS_SHOWN = 'RESET_PASSWORD_IS_SHOWN';
export const USER_LOGIN_INFO = 'USER_LOGIN_INFO';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const PARKING_CREATING_SUCCESS = 'PARKING_CREATING_SUCCESS';

export const PERSONAL_VEHICLES_RESPONSE = 'PERSONAL_VEHICLES_RESPONSE';
export const PERSONAL_PAYMENT_METHODS = 'PERSONAL_PAYMENT_METHODS';

export const SESSIONS = 'SESSIONS';

export const RESET_PARKING_INFO = 'RESET_PARKING_INFO';
export const RESET_PAY_PARKING_INFO = 'RESET_PAY_PARKING_INFO';
export const RESET_PERSONAL_DATA = 'RESET_PERSONAL_DATA';

export const INIT_FILTERS = 'INIT_FILTERS';
export const SET_DISTANCE_FILTER = 'SET_DISTANCE_FILTER';
export const SET_FEATURE_FILTER = 'SET_FEATURE_FILTER';

export const MAP_CONTEXT = 'MAP_CONTEXT';
